# Generated by Django 4.1.2 on 2022-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_booking_date_from_booking_date_to_booking_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
